# Generated by Django 3.2.3 on 2021-05-26 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last name')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('post_code', models.IntegerField(verbose_name='Post code')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'verbose_name': 'customer_address',
                'verbose_name_plural': 'customer_addresses',
                'db_table': 'customer_addresses',
            },
        ),
    ]
