# Generated by Django 3.2.3 on 2021-06-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='Is ordered'),
        ),
    ]
