# Generated by Django 3.2.3 on 2021-08-04 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_ordered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Order product', 'verbose_name_plural': 'Orders products'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='promocode',
        ),
        migrations.AlterField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='Заказ оформлен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_checkout',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time checkout'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time created'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time delivery'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.order', verbose_name='Order'),
        ),
        migrations.AlterModelTable(
            name='orderproduct',
            table='orders_products',
        ),
    ]
